version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LLM_SECRET_KEY=${LLM_SECRET_KEY}
      - DATABASE_URL=mysql://root:zyrl_root@db:3306/aissistant
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=zyrl_root
      - MYSQL_DATABASE=aissistant
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 