"""add_exercises_logs

Revision ID: f1468adc9ee1
Revises: 5ae1426aa0db
Create Date: 2025-05-06 20:10:28.441859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1468adc9ee1'
down_revision: Union[str, None] = '5ae1426aa0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_parts', sa.String(length=250), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_logs_id'), 'exercises_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_logs_id'), table_name='exercises_logs')
    op.drop_table('exercises_logs')
    # ### end Alembic commands ###
